apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: components-api
  labels:
    name: components-api
# TODO: add some real rules as needed
rules:
  - apiGroups:
      - toolforge.org
    resources:
      - toolconfigs
      - tooldeployments
      - deploytokens
    verbs:
      - "*"
