---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: components-api
  labels:
    name: components-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: components-api
subjects:
  - kind: ServiceAccount
    name: components-api
    namespace: components-api
