apiVersion: v1
kind: Service
metadata:
  name: components-api
  labels:
    name: components-api
spec:
  ports:
    - name: api
      port: 8443
      targetPort: 8443
  selector:
    name: components-api
