default_language_version:
  python: python3

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        verbose: true
        exclude: "(^components/gen/|^tests/)"
        args: ["--show-error-codes", "--strict"]
        additional_dependencies:
          [
            "pydantic",
            "pydantic_settings",
            "types-toml",
            "fastapi",
            "types-PyYAML",
            "toolforge-weld",
            "types-requests",
            "prometheus-client",
            "prometheus-fastapi-instrumentator",
            "jsonref",
            "types-PyYAML",
          ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-merge-conflict

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck

  - repo: local
    hooks:
      - id: export-openapi
        name: export openapi spec
        entry: poetry run python openapi/export-openapi.py components.main:create_app
        language: system
        pass_filenames: false

  # has to run after exporting the openapi spec
  - repo: https://gitlab.wikimedia.org/repos/cloud/cicd/gitlab-ci
    rev: c8124a71f14bba4d761e43d7ccf9ed6a0edf17a7
    hooks:
      - id: check-openapi-version-bump
