openapi: 3.1.0
info:
  title: Toolforge Components API
  version: 0.1.0
paths:
  /metrics:
    get:
      summary: Metrics
      description: Endpoint that serves Prometheus metrics.
      operationId: metrics
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /v1/healthz:
    get:
      summary: Healthz
      operationId: healthz
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_HealthState_'
  /v1/tool/{toolname}/config:
    get:
      tags:
      - tool
      summary: Get Tool Config
      description: Retrieve the configuration for a specific tool.
      operationId: get_tool_config
      security:
      - APIKeyHeader: []
      parameters:
      - name: toolname
        in: path
        required: true
        schema:
          type: string
          title: Toolname
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_ToolConfig_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - tool
      summary: Update Tool Config
      description: Update or create the configuration for a specific tool.
      operationId: update_tool_config
      security:
      - APIKeyHeader: []
      parameters:
      - name: toolname
        in: path
        required: true
        schema:
          type: string
          title: Toolname
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ToolConfig-Input'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_ToolConfig_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - tool
      summary: Delete Tool Config
      description: Delete the configuration for a specific tool.
      operationId: delete_tool_config
      security:
      - APIKeyHeader: []
      parameters:
      - name: toolname
        in: path
        required: true
        schema:
          type: string
          title: Toolname
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_ToolConfig_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/tool/{toolname}/deployment/token:
    get:
      tags:
      - tool
      summary: Get Tool Deploy Token
      operationId: get_tool_deploy_token
      security:
      - APIKeyHeader: []
      parameters:
      - name: toolname
        in: path
        required: true
        schema:
          type: string
          title: Toolname
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_DeployToken_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - tool
      summary: Create Tool Deploy Token
      operationId: create_tool_deploy_token
      security:
      - APIKeyHeader: []
      parameters:
      - name: toolname
        in: path
        required: true
        schema:
          type: string
          title: Toolname
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_DeployToken_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      tags:
      - tool
      summary: Update Tool Deploy Token
      operationId: update_tool_deploy_token
      security:
      - APIKeyHeader: []
      parameters:
      - name: toolname
        in: path
        required: true
        schema:
          type: string
          title: Toolname
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_DeployToken_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - tool
      summary: Delete Tool Deploy Token
      operationId: delete_tool_deploy_token
      security:
      - APIKeyHeader: []
      parameters:
      - name: toolname
        in: path
        required: true
        schema:
          type: string
          title: Toolname
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_DeployToken_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/tool/{toolname}/deployment/{deployment_id}:
    get:
      tags:
      - tool
      summary: Get Tool Deployment
      description: Retrieve the configuration for a specific tool.
      operationId: get_tool_deployment
      security:
      - APIKeyHeader: []
      parameters:
      - name: toolname
        in: path
        required: true
        schema:
          type: string
          title: Toolname
      - name: deployment_id
        in: path
        required: true
        schema:
          type: string
          title: Deployment Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_Deployment_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      tags:
      - tool
      summary: Delete Tool Deployment
      operationId: delete_tool_deployment
      security:
      - APIKeyHeader: []
      parameters:
      - name: toolname
        in: path
        required: true
        schema:
          type: string
          title: Toolname
      - name: deployment_id
        in: path
        required: true
        schema:
          type: string
          title: Deployment Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_Deployment_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /v1/tool/{toolname}/deployment:
    get:
      tags:
      - tool
      summary: List Tool Deployments
      description: List all deployments for a specific tool.
      operationId: list_tool_deployments
      security:
      - APIKeyHeader: []
      parameters:
      - name: toolname
        in: path
        required: true
        schema:
          type: string
          title: Toolname
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_DeploymentList_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      tags:
      - tool
      summary: Create Tool Deployment
      description: Create a new tool deployment.
      operationId: create_tool_deployment
      security:
      - APIKeyHeader: []
      - APIKeyQuery: []
      parameters:
      - name: toolname
        in: path
        required: true
        schema:
          type: string
          title: Toolname
      - name: force-build
        in: query
        required: false
        schema:
          type: boolean
          title: Force Build
          description: By default the component is only rebuilt if there was a change
            in the source code and there's no build for that same commit. To force
            a re-build regardless of the source code status, use force-build
          default: false
        description: By default the component is only rebuilt if there was a change
          in the source code and there's no build for that same commit. To force a
          re-build regardless of the source code status, use force-build
      - name: force-run
        in: query
        required: false
        schema:
          type: boolean
          title: Force Run
          description: By default an already running component is not restarted if
            there are no changes to the run parameters. To force a re-run regardless
            of the run parameters, use force-run
          default: false
        description: By default an already running component is not restarted if there
          are no changes to the run parameters. To force a re-run regardless of the
          run parameters, use force-run
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse_Deployment_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    ApiResponse_DeployToken_:
      properties:
        data:
          $ref: '#/components/schemas/DeployToken'
        messages:
          $ref: '#/components/schemas/ResponseMessages'
          default:
            info: []
            warning:
            - You are using a beta feature of Toolforge.
            error: []
      type: object
      required:
      - data
      title: ApiResponse[DeployToken]
    ApiResponse_DeploymentList_:
      properties:
        data:
          $ref: '#/components/schemas/DeploymentList'
        messages:
          $ref: '#/components/schemas/ResponseMessages'
          default:
            info: []
            warning:
            - You are using a beta feature of Toolforge.
            error: []
      type: object
      required:
      - data
      title: ApiResponse[DeploymentList]
    ApiResponse_Deployment_:
      properties:
        data:
          $ref: '#/components/schemas/Deployment'
        messages:
          $ref: '#/components/schemas/ResponseMessages'
          default:
            info: []
            warning:
            - You are using a beta feature of Toolforge.
            error: []
      type: object
      required:
      - data
      title: ApiResponse[Deployment]
    ApiResponse_HealthState_:
      properties:
        data:
          $ref: '#/components/schemas/HealthState'
        messages:
          $ref: '#/components/schemas/ResponseMessages'
          default:
            info: []
            warning:
            - You are using a beta feature of Toolforge.
            error: []
      type: object
      required:
      - data
      title: ApiResponse[HealthState]
    ApiResponse_ToolConfig_:
      properties:
        data:
          $ref: '#/components/schemas/ToolConfig-Output'
        messages:
          $ref: '#/components/schemas/ResponseMessages'
          default:
            info: []
            warning:
            - You are using a beta feature of Toolforge.
            error: []
      type: object
      required:
      - data
      title: ApiResponse[ToolConfig]
    ComponentInfo:
      properties:
        component_type:
          type: string
          const: continuous
          title: Component Type
        build:
          $ref: '#/components/schemas/SourceBuildInfo'
        run:
          $ref: '#/components/schemas/RunInfo'
      type: object
      required:
      - component_type
      - build
      - run
      title: ComponentInfo
    DeployToken:
      properties:
        token:
          type: string
          format: uuid
          title: Token
        creation_date:
          type: string
          format: date-time
          title: Creation Date
      type: object
      title: DeployToken
    Deployment:
      properties:
        deploy_id:
          type: string
          title: Deploy Id
        creation_time:
          type: string
          title: Creation Time
        builds:
          additionalProperties:
            $ref: '#/components/schemas/DeploymentBuildInfo'
          type: object
          title: Builds
        runs:
          additionalProperties:
            $ref: '#/components/schemas/DeploymentRunInfo'
          type: object
          title: Runs
        status:
          $ref: '#/components/schemas/DeploymentState'
          default: pending
        long_status:
          type: string
          title: Long Status
          default: ''
        force_build:
          type: boolean
          title: Force Build
          default: false
        force_run:
          type: boolean
          title: Force Run
          default: false
      type: object
      required:
      - deploy_id
      - creation_time
      - builds
      - runs
      title: Deployment
    DeploymentBuildInfo:
      properties:
        build_id:
          anyOf:
          - type: string
          - type: string
            enum:
            - no-id-yet
            - no-build-needed
          title: Build Id
        build_status:
          $ref: '#/components/schemas/DeploymentBuildState'
      type: object
      required:
      - build_id
      - build_status
      title: DeploymentBuildInfo
    DeploymentBuildState:
      type: string
      enum:
      - pending
      - running
      - failed
      - successful
      - unknown
      - skipped
      title: DeploymentBuildState
    DeploymentList:
      properties:
        deployments:
          items:
            $ref: '#/components/schemas/Deployment'
          type: array
          title: Deployments
      type: object
      required:
      - deployments
      title: DeploymentList
    DeploymentRunInfo:
      properties:
        run_status:
          $ref: '#/components/schemas/DeploymentRunState'
        run_long_status:
          type: string
          title: Run Long Status
          default: ''
      type: object
      required:
      - run_status
      title: DeploymentRunInfo
    DeploymentRunState:
      type: string
      enum:
      - pending
      - failed
      - successful
      - skipped
      - unknown
      title: DeploymentRunState
      description: 'This are the states a run can be in


        A run being an execution of a component (ex. running a continuous job, or
        creating a new scheduled job).'
    DeploymentState:
      type: string
      enum:
      - pending
      - running
      - failed
      - timed_out
      - successful
      title: DeploymentState
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    HealthState:
      properties:
        status:
          type: string
          enum:
          - OK
          - ERROR
          title: Status
      type: object
      required:
      - status
      title: HealthState
    ResponseMessages:
      properties:
        info:
          items:
            type: string
          type: array
          title: Info
          default: []
        warning:
          items:
            type: string
          type: array
          title: Warning
          default:
          - You are using a beta feature of Toolforge.
        error:
          items:
            type: string
          type: array
          title: Error
          default: []
      type: object
      title: ResponseMessages
    RunInfo:
      properties:
        command:
          type: string
          title: Command
        port:
          anyOf:
          - type: integer
          - type: 'null'
          title: Port
        health_check_script:
          anyOf:
          - type: string
          - type: 'null'
          title: Health Check Script
        health_check_http:
          anyOf:
          - type: string
          - type: 'null'
          title: Health Check Http
      type: object
      required:
      - command
      title: RunInfo
    SourceBuildInfo:
      properties:
        repository:
          type: string
          title: Repository
        ref:
          type: string
          title: Ref
      type: object
      required:
      - repository
      - ref
      title: SourceBuildInfo
    ToolConfig-Input:
      properties:
        config_version:
          anyOf:
          - type: string
            const: v1beta1
          - type: 'null'
          title: Config Version
          default: v1beta1
        components:
          additionalProperties:
            $ref: '#/components/schemas/ComponentInfo'
          type: object
          minProperties: 1
          title: Components
      type: object
      required:
      - components
      title: ToolConfig
    ToolConfig-Output:
      properties:
        config_version:
          anyOf:
          - type: string
            const: v1beta1
          - type: 'null'
          title: Config Version
          default: v1beta1
        components:
          additionalProperties:
            $ref: '#/components/schemas/ComponentInfo'
          type: object
          minProperties: 1
          title: Components
      type: object
      required:
      - components
      title: ToolConfig
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: x-toolforge-tool
    APIKeyQuery:
      type: apiKey
      in: query
      name: token
