---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: toolconfigs.components-api.toolforge.org
  labels:
    app.kubernetes.io/part-of: toolforge-components-api
    version: v1
spec:
  group: components-api.toolforge.org
  scope: Namespaced
  names:
    kind: ToolConfig
    plural: toolconfigs
    singular: toolconfig
    categories:
      - toolforge
      - components-api
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          # One can use x-kubernetes-preserve-unknown-fields: true
          # at the root of the schema (and inside any properties, additionalProperties)
          # to get the traditional CRD behaviour that nothing is pruned, despite
          # setting spec.preserveUnknownProperties: false.
          #
          # See https://kubernetes.io/blog/2019/06/20/crd-structural-schema/
          # See issue: https://github.com/knative/serving/issues/912
          x-kubernetes-preserve-unknown-fields: true
